# use loss mask
diffusion:
  predict_xstart: True
  use_loss_mask: True

decoder:
  len_dec: 16
  frame_size: 1
  zero: True
  spec_num_frames: 32

latent:
  latent_size: 0 # no latent space. no encoder

training:
  lr: 2.0e-5
#  resume_checkpoint: "log/16bar_scratch/model350000.pt"

sampling:
  batch_size: 4
  num_samples: 4
  model_path: "log/16bar_v_scratch_zero_lm/ema_0.9999_2700000.pt"
  use_ddim: True