diffusion:
  predict_xstart: True

decoder:
  len_dec: 16
  frame_size: 1
  zero: True

latent:
  latent_size: 0 # no latent space. no encoder

training:
  lr: 2.0e-5
#  resume_checkpoint: "log/16bar_scratch/model350000.pt"