decoder:
  len_dec: 2 # 2 bars

latent:
  latent_size: 0 # no latent space. no encoder

training:
  lr: 2.0e-5
  resume_checkpoint: "/home/eri24816/improved-diffusion/log/2bar_scratch_newds/model1200000.pt"
