# use loss mask
data_dir: /home/eri24816/pianoroll_split
diffusion:
  predict_xstart: True
  use_loss_mask: True

decoder:
  len_dec: 16
  frame_size: 1
  zero: True

latent:
  latent_size: 0 # no latent space. no encoder

training:
  lr: 2.0e-5
  one_bar_steps: 2_000_000
  save_interval: 100_000

sampling:
  batch_size: 4
  num_samples: 32
  use_ddim: False
  model_path: "log/a_vdiff/ema_0.9999_4200000.pt"